/*
Proyecto Recoleccion de basura - Script para cargar datos iniciales a la base de datos 
Estudiantes: Delvis Cruz y Jose Peñalba
*/

--Seleccionando base de datos
USE DB_RECOLECCION;

--Datos iniciales para la tabla de usuarios
INSERT INTO TB_USUARIOS (USERNAME, PASSWD, ROL)
VALUES ('ADMIN', 'CONTRASENIA', 1);

INSERT INTO TB_USUARIOS (USERNAME, PASSWD, ROL)
VALUES ('jpvisor', 'CONTRASENIA', 2);

INSERT INTO TB_USUARIOS (USERNAME, PASSWD, ROL, NOMBRE)
VALUES ('dcvisor', 'CONTRASENIA', 2, 'Delvis Cruz');

-- Datos iniciales para la tabla de basureros
INSERT INTO TB_BASUREROS (DETALLE_UBICACION, COORDENADAS, TIPO_BASURERO)
VALUES ('Se encuentra en la entrada de la UTP', '55.53246,80.256116', 1);

INSERT INTO TB_BASUREROS (DETALLE_UBICACION, COORDENADAS, TIPO_BASURERO)
VALUES ('Se encuentra dentro de la universidad', '55.37881,80.677913', 1);

--Datos iniciales de la tabla historica de los basureros
INSERT INTO TB_DATA_HISTORICA (ID_BASURERO, FECHA_VACIO, FECHA_LLENADO)
VALUES (1, '2023-10-17 07:00:00', '2023-10-17 18:37:00');

INSERT INTO TB_DATA_HISTORICA (ID_BASURERO, FECHA_VACIO, FECHA_LLENADO)
VALUES (2, '2023-10-16 10:00:00', '2023-10-17 15:39:00');


USE [master]
GO
CREATE LOGIN [user_conexion] WITH PASSWORD=N'albondiga', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [user_conexion]
GO

UPDATE TB_BASUREROS	SET NUM_CONTENEDORES = '2' WHERE ID_BASURERO = 2 
UPDATE TB_BASUREROS	SET NUM_CONTENEDORES = '1' WHERE ID_BASURERO = 1 

UPDATE TB_USUARIOS SET NOMBRE = 'ADMINISTRADOR' WHERE ID_USUARIO = 1
UPDATE TB_USUARIOS SET NOMBRE = 'Jose Peñalba' WHERE ID_USUARIO = 2
SELECT * FROM TB_USUARIOS